"""Add venue and band views to session

Revision ID: 0fb4cd7fddcd
Revises: 1c392b60c823
Create Date: 2025-06-11 23:00:12.650270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fb4cd7fddcd'
down_revision = '1c392b60c823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_venues_viewded', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('num_bands_viewed', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_column('num_bands_viewed')
        batch_op.drop_column('num_venues_viewded')

    # ### end Alembic commands ###
