"""Add more info to band table

Revision ID: 1c392b60c823
Revises: f011b8b8a189
Create Date: 2025-06-11 11:50:27.764347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c392b60c823'
down_revision = 'f011b8b8a189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('band', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('instagram_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('website_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('band', schema=None) as batch_op:
        batch_op.drop_column('website_url')
        batch_op.drop_column('instagram_url')
        batch_op.drop_column('facebook_url')

    # ### end Alembic commands ###
