"""Added town and video id

Revision ID: 4604e19b51e2
Revises: 9baa1582d949
Create Date: 2025-05-15 19:34:41.223281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4604e19b51e2'
down_revision = '9baa1582d949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('band', schema=None) as batch_op:
        batch_op.add_column(sa.Column('youtube_ids', sa.ARRAY(sa.String()), nullable=True))

    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('town', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.drop_column('town')

    with op.batch_alter_table('band', schema=None) as batch_op:
        batch_op.drop_column('youtube_ids')

    # ### end Alembic commands ###
