"""Added Venue and Band tables

Revision ID: 5cfdf03e991e
Revises: a3c4d7177514
Create Date: 2025-04-28 13:53:43.631517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cfdf03e991e'
down_revision = 'a3c4d7177514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('band',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('band_name', sa.String(length=50), nullable=False),
    sa.Column('band_type', sa.String(), nullable=False),
    sa.Column('tribute_band_name', sa.String(), nullable=False),
    sa.Column('genres', sa.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_name', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('county', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('band_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'venue', ['venue_id'], ['id'])
        batch_op.create_foreign_key(None, 'band', ['band_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('band_id')
        batch_op.drop_column('venue_id')

    op.drop_table('venue')
    op.drop_table('band')
    # ### end Alembic commands ###
