"""Update session table

Revision ID: 69c07f5f21cc
Revises: e00cba5c75de
Create Date: 2025-06-03 19:25:47.634736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69c07f5f21cc'
down_revision = 'e00cba5c75de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agent', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('referer', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_column('referer')
        batch_op.drop_column('user_agent')

    # ### end Alembic commands ###
