"""Added email creds table

Revision ID: 6e65cc679d53
Revises: a32c74f14fd1
Create Date: 2025-07-20 11:16:07.660882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e65cc679d53'
down_revision = 'a32c74f14fd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_creds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_access_token', sa.LargeBinary(), nullable=False),
    sa.Column('google_expiry', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_creds')
    # ### end Alembic commands ###
