"""Updated visit

Revision ID: 79902f9bfa20
Revises: ab04a06b7f1d
Create Date: 2024-12-04 01:31:15.611569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79902f9bfa20'
down_revision = 'ab04a06b7f1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page', sa.String(), nullable=False))
        batch_op.drop_column('path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('page')

    # ### end Alembic commands ###
