"""Add more info to user table

Revision ID: 8d02e1f7fe38
Revises: 932f93e78cf3
Create Date: 2025-06-03 16:40:41.749736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d02e1f7fe38'
down_revision = '932f93e78cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('user_agents', sa.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('ip_addresses', sa.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('referers', sa.ARRAY(sa.String()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('referers')
        batch_op.drop_column('ip_addresses')
        batch_op.drop_column('user_agents')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
