"""Made email cred columns strings instead

Revision ID: 965a213a855f
Revises: 6e65cc679d53
Create Date: 2025-07-20 14:06:44.137558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '965a213a855f'
down_revision = '6e65cc679d53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_creds', schema=None) as batch_op:
        batch_op.alter_column('google_access_token',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('google_expiry',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_creds', schema=None) as batch_op:
        batch_op.alter_column('google_expiry',
               existing_type=sa.String(),
               type_=postgresql.BYTEA(),
               existing_nullable=False)
        batch_op.alter_column('google_access_token',
               existing_type=sa.String(),
               type_=postgresql.BYTEA(),
               existing_nullable=False)

    # ### end Alembic commands ###
