"""Removed venue fields from event table

Revision ID: 9baa1582d949
Revises: a517a25eb876
Create Date: 2025-05-02 21:27:38.071415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9baa1582d949'
down_revision = 'a517a25eb876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('county')
        batch_op.drop_column('venue_name')
        batch_op.drop_column('address')
        batch_op.drop_column('lng')
        batch_op.drop_column('lat')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('venue_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('county', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
