"""Video click now cascades when event is deleted

Revision ID: a32c74f14fd1
Revises: 0fb4cd7fddcd
Create Date: 2025-06-20 14:36:02.627407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a32c74f14fd1'
down_revision = '0fb4cd7fddcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_click', schema=None) as batch_op:
        batch_op.drop_constraint('video_click_event_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'event', ['event_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_click', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('video_click_event_id_fkey', 'event', ['event_id'], ['id'])

    # ### end Alembic commands ###
