"""Added place_id to venue

Revision ID: a517a25eb876
Revises: 5cfdf03e991e
Create Date: 2025-05-02 20:11:36.880214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a517a25eb876'
down_revision = '5cfdf03e991e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('band_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('place_id', sa.String(), nullable=True))
        batch_op.alter_column('county',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.alter_column('county',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('place_id')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('band_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
