"""Made county field required

Revision ID: c94bf291e6c2
Revises: a3c4d7177514
Create Date: 2025-03-01 20:16:42.543132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c94bf291e6c2'
down_revision = 'a3c4d7177514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('county',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('county',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
