"""Make added fields required

Revision ID: dca3c6eb6a71
Revises: 4604e19b51e2
Create Date: 2025-05-15 21:23:48.829270

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dca3c6eb6a71'
down_revision = '4604e19b51e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('band', schema=None) as batch_op:
        batch_op.alter_column('youtube_ids',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)

    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.alter_column('place_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('town',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.alter_column('town',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('place_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('band', schema=None) as batch_op:
        batch_op.alter_column('youtube_ids',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)

    # ### end Alembic commands ###
