"""Added distance formatted

Revision ID: dd76216f52b4
Revises: 082c1f53e22b
Create Date: 2024-11-26 13:43:18.009700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd76216f52b4'
down_revision = '082c1f53e22b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_distance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distance_formatted', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_distance', schema=None) as batch_op:
        batch_op.drop_column('distance_formatted')

    # ### end Alembic commands ###
