"""Add more info to venue table

Revision ID: f011b8b8a189
Revises: a5ab77f89409
Create Date: 2025-06-07 20:15:55.921823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f011b8b8a189'
down_revision = 'a5ab77f89409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('facebook_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('instagram_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('website_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.drop_column('website_url')
        batch_op.drop_column('instagram_url')
        batch_op.drop_column('facebook_url')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
