"""Added more tracking to the query table

Revision ID: f02edbc7a666
Revises: dca3c6eb6a71
Create Date: 2025-05-18 11:16:55.978662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f02edbc7a666'
down_revision = 'dca3c6eb6a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agent', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('referer', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query', schema=None) as batch_op:
        batch_op.drop_column('referer')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('user_agent')

    # ### end Alembic commands ###
